version = 1

exclude_patterns = [
    "ssrspeed/resource/**",
    "ssrspeed/speedtest/methods/speedtestnet.py",
]

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[analyzers.meta]
runtime_version = "3.8.13"
type_checker = "mypy"
max_line_length = 88

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true
