[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3
verbose = true

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
exclude = ["venv"]
show_error_codes = true

[[tool.mypy.overrides]]
module = [
  "ssrspeed.speedtest.methods.*"
]
ignore_errors = true
