[tool.black]
line-length = 88
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["ssrspeed", "tests"]

[tool.pylint.master]
job = 0
suggestion-mode = "yes"

[tool.pylint.basic]
argument-naming-style = "any"
variable-naming-style = "any"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.message_control]
disable = [
  "broad-except",
  "consider-using-with",
  "import-outside-toplevel",
  "missing-docstring",
  "pointless-string-statement",
]

[tool.pylint.design]
min-public-methods = 0
max-returns = 8

[tool.mypy]
python_version = 3.8
exclude = ["build|dist|venv"]
ignore_missing_imports = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["ssrspeed.speedtest.methods.*"]
ignore_errors = true
