name: Help wanted 求助
description: 在提出问题前请先升级到最新版本，同时也请通过搜索确认是否有人提出过相同问题。
title: "[Help wanted]: "
labels: ["help wanted"]
body:
  - type: dropdown
    id: os
    attributes:
      label: "操作系统"
      description: "描述软件运行的操作系统"
      multiple: false
      options:
        - Ubuntu - Linux
        - Debian - Linux
        - CentOS - Linux
        - Arch - Linux
        - Mac AMD64
        - Mac M1
        - Windows
        - Others
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "实际情况"
      description: "描述实际发生了什么"
    validations:
      required: true
  - type: textarea
    id: "reproduction-method"
    attributes:
      label: "复现方法"
      description: "BUG 出现前执行的操作 / 输入的命令，注意隐去重要/隐私信息"
      placeholder: 标序号
    validations:
      required: true
  - type: textarea
    id: "log"
    attributes:
      label: "日志信息"
      description: "输出错误信息，注意隐去重要/隐私信息"
      placeholder: 在日志开始和结束位置粘贴冒号后的内容：```
    validations:
      required: true
  - type: checkboxes
    id: "latest-version"
    attributes:
      label: "我确认已更新至最新版本"
      description: "否则请更新后尝试"
      options:
        - label: 是
          required: true
  - type: checkboxes
    id: "issues"
    attributes:
      label: "我确认已查询历史 issues"
      description: "否则请查询后提出"
      options:
        - label: 是
          required: true
